// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketsSystem.Data;

#nullable disable

namespace TicketsSystem.Data.Migrations
{
    [DbContext(typeof(SystemTicketsContext))]
    partial class SystemTicketsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketsSystem.Domain.Entities.Mcprequest", b =>
                {
                    b.Property<Guid>("McprequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MCPRequestId")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UseCase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("McprequestId")
                        .HasName("PK__MCPReque__17476F69DB750726");

                    b.HasIndex("TicketId");

                    b.ToTable("MCPRequests", (string)null);
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.Mcpresponse", b =>
                {
                    b.Property<Guid>("McpresponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MCPResponseId")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("McprequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MCPRequestId");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("McpresponseId")
                        .HasName("PK__MCPRespo__198540A99C9B3D60");

                    b.HasIndex("McprequestId");

                    b.ToTable("MCPResponses", (string)null);
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E128C070050");

                    b.HasIndex(new[] { "UserId" }, "IX_Notifications_UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TicketId")
                        .HasName("PK__Tickets__712CC60788205755");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex(new[] { "AssignedToUserId" }, "IX_Tickets_AssignedTo");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_Tickets_CreatedAt");

                    b.HasIndex(new[] { "PriorityId" }, "IX_Tickets_Priority");

                    b.HasIndex(new[] { "StatusId" }, "IX_Tickets_Status");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.TicketComment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentId")
                        .HasName("PK__TicketCo__C3B4DFCA2E78B4B3");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TicketId" }, "IX_Comments_TicketId");

                    b.ToTable("TicketComments");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.TicketHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ChangeGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HistoryId")
                        .HasName("PK__TicketHi__4D7B4ABD8C5F12E3");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex(new[] { "TicketId" }, "IX_History_TicketId");

                    b.ToTable("TicketHistory", (string)null);
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.TicketPriority", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriorityId"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PriorityId")
                        .HasName("PK__TicketPr__D0A3D0BE49B3DD32");

                    b.HasIndex(new[] { "Name" }, "UQ__TicketPr__737584F69307F0F8")
                        .IsUnique();

                    b.ToTable("TicketPriorities");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.TicketStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId")
                        .HasName("PK__TicketSt__C8EE20633E5ECBD6");

                    b.HasIndex(new[] { "Name" }, "UQ__TicketSt__737584F649C40AC9")
                        .IsUnique();

                    b.ToTable("TicketStatuses");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C755FA5C7");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105341B6078ED")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.Mcprequest", b =>
                {
                    b.HasOne("TicketsSystem.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Mcprequests")
                        .HasForeignKey("TicketId")
                        .IsRequired()
                        .HasConstraintName("FK_MCPRequest_Ticket");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.Mcpresponse", b =>
                {
                    b.HasOne("TicketsSystem.Domain.Entities.Mcprequest", "Mcprequest")
                        .WithMany("Mcpresponses")
                        .HasForeignKey("McprequestId")
                        .IsRequired()
                        .HasConstraintName("FK_MCPResponse_Request");

                    b.Navigation("Mcprequest");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.Notification", b =>
                {
                    b.HasOne("TicketsSystem.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("TicketsSystem.Domain.Entities.User", "AssignedToUser")
                        .WithMany("TicketAssignedToUsers")
                        .HasForeignKey("AssignedToUserId")
                        .HasConstraintName("FK_Tickets_AssignedTo");

                    b.HasOne("TicketsSystem.Domain.Entities.User", "CreatedByUser")
                        .WithMany("TicketCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_CreatedBy");

                    b.HasOne("TicketsSystem.Domain.Entities.TicketPriority", "Priority")
                        .WithMany("Tickets")
                        .HasForeignKey("PriorityId")
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_Priority");

                    b.HasOne("TicketsSystem.Domain.Entities.TicketStatus", "Status")
                        .WithMany("Tickets")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_Status");

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Priority");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.TicketComment", b =>
                {
                    b.HasOne("TicketsSystem.Domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketComments")
                        .HasForeignKey("TicketId")
                        .IsRequired()
                        .HasConstraintName("FK_Comments_Ticket");

                    b.HasOne("TicketsSystem.Domain.Entities.User", "User")
                        .WithMany("TicketComments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Comments_User");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.TicketHistory", b =>
                {
                    b.HasOne("TicketsSystem.Domain.Entities.User", "ChangedByUser")
                        .WithMany("TicketHistories")
                        .HasForeignKey("ChangedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_History_User");

                    b.HasOne("TicketsSystem.Domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketHistories")
                        .HasForeignKey("TicketId")
                        .IsRequired()
                        .HasConstraintName("FK_History_Ticket");

                    b.Navigation("ChangedByUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.Mcprequest", b =>
                {
                    b.Navigation("Mcpresponses");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Mcprequests");

                    b.Navigation("TicketComments");

                    b.Navigation("TicketHistories");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.TicketPriority", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.TicketStatus", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketsSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("TicketAssignedToUsers");

                    b.Navigation("TicketComments");

                    b.Navigation("TicketCreatedByUsers");

                    b.Navigation("TicketHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
